import math

WIDTH = 1200
HALF_WIDTH = WIDTH / 2
HEIGHT = 800
HALF_HEIGHT = HEIGHT / 2
FPS = 30

TILE = 100

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 400
MAX_DEPTH = 800
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJ_COEFF = 1 * DIST * TILE
SCALE = WIDTH // NUM_RAYS
